---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(name)s] %(message)s'
  formal:
    format: '[%(levelname)s] [%(asctime)s:%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: formal
    filename: hyperflow.log

# 如果设为DEBUG, sql也会下来
root:
  level: DEBUG
  handlers: [file_handler, console]

loggers:
  hyperopt.tpe:
    level: WARNING
    handlers: [file_handler]

  dsmac.intensification.intensification.Intensifier:
    level: DEBUG
    handlers: [file_handler, console]

  dsmac.optimizer.local_search.LocalSearch:
    level: DEBUG
    handlers: [file_handler, console]

  dsmac.optimizer.smbo.SMBO:
    level: DEBUG
    handlers: [file_handler, console]

  peewee:
    level: INFO
    handlers: [file_handler]
